config:
  springProfilesActive: dev  
  jpa:
    showSql: "true"
  management:
    endpointsInclude: "*"  
  logging:
    levelRoot: "INFO"
    levelApp: "DEBUG"
    levelSpringWeb: "INFO"
    levelSpringSecurity: "DEBUG"

replicaCount: 1