apiVersion: v1
kind: ConfigMap
metadata:
  name: guest-service-config
data:
  SERVER_PORT: {{ .Values.config.serverPort | quote }}
  SPRING_DATASOURCE_URL: {{ .Values.config.database.url | quote }}
  SPRING_JPA_HIBERNATE_DDL_AUTO: {{ .Values.config.jpa.ddlAuto | quote }}
  SPRING_JPA_SHOW_SQL: {{ .Values.config.jpa.showSql | quote }}
  SPRING_JPA_PROPERTIES_HIBERNATE_DEFAULT_SCHEMA: {{ .Values.config.database.schema | quote }}
  SPRING_DATASOURCE_HIKARI_MAXIMUM_POOL_SIZE: {{ .Values.config.database.poolSize | quote }}
  SPRING_DATASOURCE_HIKARI_MINIMUM_IDLE: {{ .Values.config.database.poolMinIdle | quote }}
  SPRING_DATASOURCE_HIKARI_CONNECTION_TIMEOUT: {{ .Values.config.database.connTimeout | quote }}
  SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI: {{ .Values.config.keycloak.issuerUri | quote }}
  SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK_SET_URI: {{ .Values.config.keycloak.jwkSetUri | quote }}
  SPRING_KAFKA_BOOTSTRAP_SERVERS: {{ .Values.config.kafka.bootstrapServers | quote }}
  SPRING_KAFKA_CONSUMER_GROUP_ID: {{ .Values.config.kafka.consumerGroup | quote }}
  SPRING_KAFKA_CONSUMER_AUTO_OFFSET_RESET: {{ .Values.config.kafka.autoOffsetReset | quote }}
  SPRING_FLYWAY_ENABLED: {{ .Values.config.flyway.enabled | quote }}
  SPRING_FLYWAY_SCHEMAS: {{ .Values.config.database.schema | quote }}
  SPRING_FLYWAY_DEFAULT_SCHEMA: {{ .Values.config.database.schema | quote }}
  LOGGING_LEVEL_ROOT: {{ .Values.config.logging.levelRoot | quote }}
  LOGGING_LEVEL_COM_PLANIFY: {{ .Values.config.logging.levelApp | quote }}
  LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_WEB: {{ .Values.config.logging.levelSpringWeb | quote }}
  LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_SECURITY: {{ .Values.config.logging.levelSpringSecurity | quote }}
  SPRING_PROFILES_ACTIVE: {{ .Values.config.springProfilesActive | quote }}