apiVersion: v1
kind: Service
metadata:
  name: guest-service
spec:
  type: {{ .Values.service.type }}
  selector:
    app: guest-service
  ports:
  - protocol: TCP
    port: {{ .Values.service.port }}
    targetPort: {{ .Values.service.targetPort }}